Repository Diaring/Diaring-Android, pull requests merged in 2022-06, with the labels that each got.

#17 Yb signup
  Diaring/app/build.gradle
  Diaring/app/src/main/AndroidManifest.xml
  Diaring/app/src/main/java/com/oss/diaring/presentation/main/MainActivity.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/signup/SignUpActivity.kt
  Diaring/app/src/main/res/drawable/bg_rectangle.xml
  Diaring/app/src/main/res/drawable/bg_rectangle2.xml
  Diaring/app/src/main/res/layout/activity_sign_up.xml
Labels: layout, Done, 영범

#23 Feat/19 local storage setup
  Diaring/app/src/main/AndroidManifest.xml
  Diaring/app/src/main/java/com/oss/diaring/DiaringApplication.kt
  Diaring/app/src/main/java/com/oss/diaring/data/DATA_README.md
  Diaring/app/src/main/java/com/oss/diaring/data/sharedpreference/SharedPrefManager.kt
  Diaring/app/src/main/java/com/oss/diaring/data/sharedpreference/SharedPrefManagerImpl.kt
  Diaring/app/src/main/java/com/oss/diaring/domain/DOMAIN_README.md
  Diaring/app/src/main/java/com/oss/diaring/util/Constants.kt
  Diaring/app/src/main/java/com/oss/diaring/util/UTIL_README.md
Labels: feat, In Progress, 재성:zany_face:

#29 [FEAT] #16 로그인 액티비티 구현
  Diaring/app/src/main/AndroidManifest.xml
  Diaring/app/src/main/java/com/oss/diaring/data/sharedpreference/SharedPrefManager.kt
  Diaring/app/src/main/java/com/oss/diaring/data/sharedpreference/SharedPrefManagerImpl.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/login/LoginActivity.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/splashScreen/SplashActivity.kt
  Diaring/app/src/main/java/com/oss/diaring/util/Constants.kt
  Diaring/app/src/main/res/drawable/round_background.xml
  Diaring/app/src/main/res/drawable/textbox_edge.xml
  Diaring/app/src/main/res/layout/activity_login.xml
Labels: layout, feat, Done, 솔

#30 [FEAT]#26 마이페이지 구현
  Diaring/app/build.gradle
  Diaring/app/src/main/java/com/oss/diaring/data/sharedpreference/SharedPrefManagerImpl.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/login/LoginActivity.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/mypage/MypageFragment.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/signup/SignUpActivity.kt
  Diaring/app/src/main/res/layout/activity_sign_up.xml
  Diaring/app/src/main/res/layout/fragment_mypage.xml
  Diaring/build.gradle
Labels: feat, Done, 영범

#31 [DOCS] #27 Readme 수정
  README.md
Labels: Done, docs, 나경

#33 [FEAT] #32 마이페이지, 회원가입, 로그인 ver.2
  Diaring/app/src/main/java/com/oss/diaring/presentation/login/LoginActivity.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/mypage/MypageFragment.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/signup/DataModel.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/signup/SignUpActivity.kt
  Diaring/app/src/main/res/layout/fragment_mypage.xml
Labels: layout, feat, Done, modify, 영범

#34 Feat/19 local storage setup
  Diaring/app/build.gradle
  Diaring/app/src/main/AndroidManifest.xml
  Diaring/app/src/main/java/com/oss/diaring/DiaringApplication.kt
  Diaring/app/src/main/java/com/oss/diaring/data/database/DiaryDatabase.kt
  Diaring/app/src/main/java/com/oss/diaring/data/database/converter/BitmapConverter.kt
  Diaring/app/src/main/java/com/oss/diaring/data/database/converter/DateConverter.kt
  Diaring/app/src/main/java/com/oss/diaring/data/database/converter/ListConverter.kt
  Diaring/app/src/main/java/com/oss/diaring/data/database/dao/DiaryDao.kt
  Diaring/app/src/main/java/com/oss/diaring/data/database/entity/DailyEmojis.kt
  Diaring/app/src/main/java/com/oss/diaring/data/database/entity/DailyWeather.kt
  Diaring/app/src/main/java/com/oss/diaring/data/database/entity/Diary.kt
  Diaring/app/src/main/java/com/oss/diaring/data/datasource/DiaryLocalDataSource.kt
  Diaring/app/src/main/java/com/oss/diaring/data/datasource/DiaryLocalDataSourceImpl.kt
  Diaring/app/src/main/java/com/oss/diaring/data/model/DayWithEmojiAndSelect.kt
  Diaring/app/src/main/java/com/oss/diaring/data/model/DayWithWeather.kt
  Diaring/app/src/main/java/com/oss/diaring/data/model/DiaryWithDailyEmoji.kt
  Diaring/app/src/main/java/com/oss/diaring/data/model/MonthlyCalendar.kt
  Diaring/app/src/main/java/com/oss/diaring/data/repository/DiaryRepository.kt
  Diaring/app/src/main/java/com/oss/diaring/data/repository/DiaryRepositoryImpl.kt
  Diaring/app/src/main/java/com/oss/diaring/di/DiaryDatabaseModule.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/Onboarding/OnboardingActivity.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/Onboarding/OnboardingFragment1.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/Onboarding/OnboardingFragment2.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/Onboarding/OnboardingFragment3.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/Onboarding/OnboardingFragment4.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/Onboarding/OnboardingFragment5.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/calendar/adapter/DateAdapter.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/calendar/adapter/MonthAdapter.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/dashboard/DashboardFragment.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/home/HomeFragment.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/home/HomeViewModel.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/home/calendar/CalendarFragment.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/home/calendar/CalendarViewModel.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/home/calendar/EmotionEmojiBottomSheetDialog.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/home/calendar/adapter/CalendarAdapter.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/home/calendar/adapter/CalendarDayAdapter.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/home/calendar/adapter/CalendarViewPagerAdapter.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/login/LoginActivity.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/main/MainActivity.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/mypage/MypageFragment.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/signup/SignUpActivity.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/splashScreen/SplashActivity.kt
  Diaring/app/src/main/java/com/oss/diaring/util/Constants.kt
  Diaring/app/src/main/java/com/oss/diaring/util/DayClickListener.kt
  Diaring/app/src/main/java/com/oss/diaring/util/EmojiSwipeListener.kt
  Diaring/app/src/main/java/com/oss/diaring/util/Enums.kt
  Diaring/app/src/main/java/com/oss/diaring/util/MonthSwipeListener.kt
  Diaring/app/src/main/java/com/oss/diaring/util/TodayClickListener.kt
  Diaring/app/src/main/res/drawable/ic_empty_calendar_24.xml
  Diaring/app/src/main/res/layout/fragment_calendar.xml
  Diaring/app/src/main/res/layout/fragment_home.xml
  Diaring/app/src/main/res/layout/item_calendar.xml
  Diaring/app/src/main/res/layout/item_calendar_date.xml
  Diaring/app/src/main/res/layout/item_calendar_day.xml
  Diaring/app/src/main/res/layout/item_calendar_month.xml
  Diaring/app/src/main/res/menu/menu_bottom_navigation.xml
  Diaring/app/src/main/res/navigation/nav_graph.xml
  Diaring/build.gradle
Labels: feat, Done, 재성:zany_face:

#36 [FEAT] #28 Connect Room with Dashboard
  Diaring/app/src/main/java/com/oss/diaring/presentation/dashboard/DashboardFragment.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/dashboard/DashboardViewModel.kt
Labels: feat, Done, 나경

#39 Fix/35 etc bug
  Diaring/app/build.gradle
  Diaring/app/src/main/AndroidManifest.xml
  Diaring/app/src/main/java/com/oss/diaring/data/database/DiaryDatabase.kt
  Diaring/app/src/main/java/com/oss/diaring/data/database/converter/BitmapConverter.kt
  Diaring/app/src/main/java/com/oss/diaring/data/database/converter/DateConverter.kt
  Diaring/app/src/main/java/com/oss/diaring/data/database/converter/ListConverter.kt
  Diaring/app/src/main/java/com/oss/diaring/data/database/dao/DiaryDao.kt
  Diaring/app/src/main/java/com/oss/diaring/data/database/entity/DailyEmojis.kt
  Diaring/app/src/main/java/com/oss/diaring/data/database/entity/DailyWeather.kt
  Diaring/app/src/main/java/com/oss/diaring/data/database/entity/Diary.kt
  Diaring/app/src/main/java/com/oss/diaring/data/datasource/DiaryLocalDataSource.kt
  Diaring/app/src/main/java/com/oss/diaring/data/datasource/DiaryLocalDataSourceImpl.kt
  Diaring/app/src/main/java/com/oss/diaring/data/model/DayWithEmojiAndSelect.kt
  Diaring/app/src/main/java/com/oss/diaring/data/model/DayWithWeather.kt
  Diaring/app/src/main/java/com/oss/diaring/data/model/MonthlyCalendar.kt
  Diaring/app/src/main/java/com/oss/diaring/data/repository/DiaryRepository.kt
  Diaring/app/src/main/java/com/oss/diaring/data/repository/DiaryRepositoryImpl.kt
  Diaring/app/src/main/java/com/oss/diaring/data/sharedpreference/SharedPrefManager.kt
  Diaring/app/src/main/java/com/oss/diaring/data/sharedpreference/SharedPrefManagerImpl.kt
  Diaring/app/src/main/java/com/oss/diaring/di/DiaryDatabaseModule.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/base/BaseActivity.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/base/BaseFragment.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/home/HomeFragment.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/home/HomeViewModel.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/home/calendar/CalendarFragment.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/home/calendar/CalendarViewModel.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/home/calendar/EmotionEmojiBottomSheetDialog.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/home/calendar/adapter/CalendarAdapter.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/home/calendar/adapter/CalendarDayAdapter.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/home/calendar/adapter/CalendarViewPagerAdapter.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/login/LoginActivity.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/main/MainActivity.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/mypage/MypageFragment.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/onboarding/OnboardingActivity.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/onboarding/OnboardingFragment1.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/onboarding/OnboardingFragment2.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/onboarding/OnboardingFragment3.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/onboarding/OnboardingFragment4.kt
  Diaring/app/src/main/java/com/oss/diaring/presentation/onboarding/OnboardingFragment5.kt
  Diaring/app/src/main/java/com/oss/diaring/util/Constants.kt
  Diaring/app/src/main/res/layout/activity_onboarding.xml
  Diaring/app/src/main/res/layout/fragment_calendar.xml
  Diaring/app/src/main/res/layout/fragment_home.xml
  Diaring/app/src/main/res/layout/fragment_onboarding1.xml
  Diaring/app/src/main/res/layout/fragment_onboarding2.xml
  Diaring/app/src/main/res/layout/fragment_onboarding3.xml
  Diaring/app/src/main/res/layout/fragment_onboarding4.xml
  Diaring/app/src/main/res/layout/fragment_onboarding5.xml
Labels: Done, fix, 재성:zany_face:
